# Generated by Django 4.0.4 on 2022-05-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user_fk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='authorization.authorization'),
        ),
    ]
