# Generated by Django 4.0.4 on 2022-05-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
