# Generated by Django 4.0.4 on 2022-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
